<?xml version="1.0"?>
<package format="2">
  <name>molab_hardware</name>
  <version>0.0.0</version>
  <description>
    Launch files and configuration for UNH's mobile lab.
  </description>

  <author email="roland@ccom.unh.edu">Roland Arsenault</author>
  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>axis_camera</depend>
  <depend>marine_ais_tools</depend>
  <depend>mru_transform</depend>
  <depend>nmea_navsat_driver</depend>
  <depend>project11</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
  
</package>
