/**/ais/nmea_relay:
  ros__parameters:
    input_type: udp
    input_port: 8010
    frame_id: molab/ais


/**/platform_sender:
  ros__parameters:
    robot_description: molab/robot_description
    width: 2.2
    length: 10.0
    reference_x: 0.2
    reference_y: 8.0
    nav:
      source_names:
      - ais
      sources:
        ais:
          topics:
            position: /molab/sensors/ais/fix
            orientation: /molab/sensors/ais/heading
            velocity: /molab/sensors/ais/vel

/**/mru_transform:
  ros__parameters:
    sensors:
      ais:
        topics: { position: 'sensors/ais/fix', orientation: 'sensors/ais/heading', velocity: 'sensors/ais/vel'}
    sensor_names:
    - ais
    base_frame: molab/base_link
    map_frame: molab/map
    odom_frame: molab/odom
